const products = [
  // Bánh kem
  {
    product_id: 1,
    category_id: 1,
    slug: "banh-kem-dau",
    name: "Bánh Kem Dâu",
    price: 120000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh kem dâu tươi",
  },
  {
    product_id: 2,
    category_id: 1,
    slug: "banh-kem-socola",
    name: "Bánh Kem Socola",
    price: 150000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh kem socola đậm vị",
  },
  {
    product_id: 3,
    category_id: 1,
    slug: "banh-kem-matcha",
    name: "Bánh Kem Matcha",
    price: 145000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh kem matcha",
  },

  // Bánh mì
  {
    product_id: 4,
    category_id: 2,
    slug: "banh-mi-bo-toi",
    name: "Bánh Mì Bơ Tỏi",
    price: 25000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh mì nướng bơ tỏi",
  },
  {
    product_id: 5,
    category_id: 2,
    slug: "banh-mi-pho-mai",
    name: "Bánh Mì Phô Mai",
    price: 30000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh mì phô mai tan chảy",
  },
  {
    product_id: 6,
    category_id: 2,
    slug: "banh-mi-trung-muoi",
    name: "Bánh Mì Trứng Muối",
    price: 35000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh mì trứng muối",
  },

  // Bánh ngọt
  {
    product_id: 7,
    category_id: 3,
    slug: "tiramisu",
    name: "Tiramisu",
    price: 90000,
    image_url: "https://placehold.co/600x400",
    description: "Tiramisu chuẩn vị Ý",
  },
  {
    product_id: 8,
    category_id: 3,
    slug: "red-velvet",
    name: "Red Velvet",
    price: 95000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh Red Velvet",
  },
  {
    product_id: 9,
    category_id: 3,
    slug: "cheese-cake",
    name: "Cheese Cake",
    price: 85000,
    image_url: "https://placehold.co/600x400",
    description: "Cheesecake mềm mịn",
  },

  // Bánh Âu
  {
    product_id: 10,
    category_id: 4,
    slug: "croissant",
    name: "Croissant",
    price: 40000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh sừng bò",
  },
  {
    product_id: 11,
    category_id: 4,
    slug: "danish-butter",
    name: "Danish Butter",
    price: 45000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh Danish bơ",
  },
  {
    product_id: 12,
    category_id: 4,
    slug: "apple-pie",
    name: "Apple Pie",
    price: 50000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh táo kiểu Âu",
  },

  // Bánh lạnh
  {
    product_id: 13,
    category_id: 5,
    slug: "mousse-dau",
    name: "Mousse Dâu",
    price: 85000,
    image_url: "https://placehold.co/600x400",
    description: "Mousse dâu mát lạnh",
  },
  {
    product_id: 14,
    category_id: 5,
    slug: "mousse-xoai",
    name: "Mousse Xoài",
    price: 85000,
    image_url: "https://placehold.co/600x400",
    description: "Mousse xoài",
  },
  {
    product_id: 15,
    category_id: 5,
    slug: "panna-cotta",
    name: "Panna Cotta",
    price: 70000,
    image_url: "https://placehold.co/600x400",
    description: "Panna cotta mềm mịn",
  },

  // Bánh sinh nhật
  {
    product_id: 16,
    category_id: 6,
    slug: "birthday-choco",
    name: "Bánh Sinh Nhật Socola",
    price: 250000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh sinh nhật socola",
  },
  {
    product_id: 17,
    category_id: 6,
    slug: "birthday-dau",
    name: "Bánh Sinh Nhật Dâu",
    price: 260000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh sinh nhật dâu",
  },
  {
    product_id: 18,
    category_id: 6,
    slug: "birthday-matcha",
    name: "Bánh Sinh Nhật Matcha",
    price: 280000,
    image_url: "https://placehold.co/600x400",
    description: "Bánh sinh nhật matcha",
  },

  // Đồ uống
  {
    product_id: 19,
    category_id: 7,
    slug: "tra-dao",
    name: "Trà Đào",
    price: 35000,
    image_url: "https://placehold.co/600x400",
    description: "Trà đào cam sả",
  },
  {
    product_id: 20,
    category_id: 7,
    slug: "ca-phe-sua",
    name: "Cà Phê Sữa",
    price: 30000,
    image_url: "https://placehold.co/600x400",
    description: "Cà phê sữa đá",
  },
  {
    product_id: 21,
    category_id: 7,
    slug: "matcha-latte",
    name: "Matcha Latte",
    price: 45000,
    image_url: "https://placehold.co/600x400",
    description: "Matcha latte",
  },
];

export default products;
